package com.example.starter.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Member
 */
public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.id
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.chName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String chname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.create_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.create_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.dept
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.domain
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.email1
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String email1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.email2
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String email2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.enName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String enname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.enabled
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private Byte enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.firstLogin
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String firstlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.kind
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.PASSWORD
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.update_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.update_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String updateUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.username
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.code
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private BigDecimal code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Member.Department
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    private BigDecimal department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.id
     *
     * @return the value of Member.id
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.id
     *
     * @param id the value for Member.id
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.chName
     *
     * @return the value of Member.chName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getChname() {
        return chname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.chName
     *
     * @param chname the value for Member.chName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setChname(String chname) {
        this.chname = chname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.create_date
     *
     * @return the value of Member.create_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.create_date
     *
     * @param createDate the value for Member.create_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.create_userid
     *
     * @return the value of Member.create_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.create_userid
     *
     * @param createUserid the value for Member.create_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.dept
     *
     * @return the value of Member.dept
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.dept
     *
     * @param dept the value for Member.dept
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.domain
     *
     * @return the value of Member.domain
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.domain
     *
     * @param domain the value for Member.domain
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.email1
     *
     * @return the value of Member.email1
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.email1
     *
     * @param email1 the value for Member.email1
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.email2
     *
     * @return the value of Member.email2
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.email2
     *
     * @param email2 the value for Member.email2
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.enName
     *
     * @return the value of Member.enName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getEnname() {
        return enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.enName
     *
     * @param enname the value for Member.enName
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setEnname(String enname) {
        this.enname = enname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.enabled
     *
     * @return the value of Member.enabled
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.enabled
     *
     * @param enabled the value for Member.enabled
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.firstLogin
     *
     * @return the value of Member.firstLogin
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getFirstlogin() {
        return firstlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.firstLogin
     *
     * @param firstlogin the value for Member.firstLogin
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setFirstlogin(String firstlogin) {
        this.firstlogin = firstlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.kind
     *
     * @return the value of Member.kind
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.kind
     *
     * @param kind the value for Member.kind
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.PASSWORD
     *
     * @return the value of Member.PASSWORD
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.PASSWORD
     *
     * @param password the value for Member.PASSWORD
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.update_date
     *
     * @return the value of Member.update_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.update_date
     *
     * @param updateDate the value for Member.update_date
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.update_userid
     *
     * @return the value of Member.update_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getUpdateUserid() {
        return updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.update_userid
     *
     * @param updateUserid the value for Member.update_userid
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setUpdateUserid(String updateUserid) {
        this.updateUserid = updateUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.username
     *
     * @return the value of Member.username
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.username
     *
     * @param username the value for Member.username
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.code
     *
     * @return the value of Member.code
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public BigDecimal getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.code
     *
     * @param code the value for Member.code
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setCode(BigDecimal code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Member.Department
     *
     * @return the value of Member.Department
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public BigDecimal getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Member.Department
     *
     * @param department the value for Member.Department
     *
     * @mbg.generated Thu Mar 31 13:52:29 CST 2022
     */
    public void setDepartment(BigDecimal department) {
        this.department = department;
    }
}