server:
  servlet:
    context-path: /start
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#   防止cookie被使用，且編碼
    session:
      cookie:
        http-only: true
        secure: true
#  port: 8081
# undertow，使用AccessLogHandler控制accesslog
  undertow:
    accesslog:
      enabled: true
#     使用默認，logs ，private File dir = new File("logs");
#      dir:
#        ../logs/access
#     使用默認 
      pattern: '{
                  "transportProtocol":"%{TRANSPORT_PROTOCOL}",
                  "scheme":"%{SCHEME}",
                  "protocol":"%{PROTOCOL}",
                  "method":"%{METHOD}",
                  "reqHeaderUserAgent":"%{i,User-Agent}",
                  "cookieUserId": "%{c,userId}",
                  "queryTest": "%{q,test}",
                  "queryString": "%q",
                  "relativePath": "%R, %{REQUEST_PATH}, %{RESOLVED_PATH}",
                  "requestLine": "%r",
                  "uri": "%U",
                  "thread": "%I",
                  "hostPort": "%{HOST_AND_PORT}",
                  "localIp": "%A",
                  "localPort": "%p",
                  "localServerName": "%v",
                  "remoteIp": "%a",
                  "remoteHost": "%h",
                  "bytesSent": "%b",
                  "time":"%{time,yyyy-MM-dd HH:mm:ss.S}",
                  "status":"%s",
                  "reason":"%{RESPONSE_REASON_PHRASE}",
                  "respHeaderUserSession":"%{o,userSession}",
                  "respCookieUserId":"%{resp-cookie,userId}",
                  "timeUsed":"%Dms, %Ts, %{RESPONSE_TIME}ms, %{RESPONSE_TIME_MICROS} us, %{RESPONSE_TIME_NANOS} ns",
                }'
      prefix: undertow_access_log.
      rotate: true
      suffix: log

#交由logbackxml配置
#logging:
#  file:
#    name: startboot.log
    
# 異動static resources 訪問路徑方式；若有異動要留意，index.html如果放在靜態資源下
# 會訪問不到
# 這邊測試是將url異動為/res，則這些請求會當成靜態資源的請求
# 
# 也可以交由WebMvcConfigurer處理
#spring:
#  mvc:
#    static-path-pattern: "/res/**"

spring:
# 何種設定啟動
  profiles:
    active:
    - dev
#  被@Deprecated，改用server servlet
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
# 這些預設值都有(ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    enabled: true
  datasource:
##   local mysql 配置
##   UTC全球標準時間，useSSL設定false，allowPublicKeyRetrieval=true；都要設定
#    url: jdbc:mysql://localhost:3306/tutorial?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
#    username: root
#    password: 1234
##   mysql 5以上，使用com.mysql.cj.jdbc.Driver。另外url需要指定
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    使用spring-boot-starter-data-jdbc默認導入的連接池為com.zaxxer.hikari.HikariDataSource，所以不用再設定
##    mybatis使用時，也會將spring-boot-starter-data-jdbc導入，因此pom也不需要特別引入
##   開啟寫也可以 
#    type: com.zaxxer.hikari.HikariDataSource
    
#   mssql配置
    url: jdbc:sqlserver://127.0.0.1:1433;databasename=tbdp;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: TBDP_WEB
    password: kangdainfo
    type: com.zaxxer.hikari.HikariDataSource

# mybatis，全局配置類盡量使用yml撰寫
mybatis:
# 全局配置類，當採用
#  config-location: classpath:mybatis/mybatis-config.xml
# mapper location
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
# scan return type pojo location
# https://blog.csdn.net/daijiguo/article/details/82827430
  type-aliases-package: com.example.starter.domain
# 當此處的全局配置類啟用，config-location則需要取消
  configuration:
    map-underscore-to-camel-case: true

# 測試 @ConfigurationProperties
pbc:
  brand: 日廠
  price: 100.12
  
---
  
spring:
  config:
    activate:
      on-profile:
      - dev
      
server:
  port: 8081
    
---
  
spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8080
  
---

# 留著紀錄
# 改用 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter/配置datasource
spring:
  config:
    activate:
      on-profile:
      - nonuse
#  datasource:
##   UTC全球標準時間，useSSL設定false，allowPublicKeyRetrieval=true；都要設定
#    url: jdbc:mysql://localhost:3306/tutorial?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
#    username: root
#    password: 1234
##   mysql 5以上，使用com.mysql.cj.jdbc.Driver。另外url需要指定
#    driver-class-name: com.mysql.cj.jdbc.Driver
#   使用spring-boot-starter-data-jdbc默認導入的連接池為com.zaxxer.hikari.HikariDataSource，所以不用再設定
#   type: com.zaxxer.hikari.HikariDataSource
#   要使用druid，需要解開pom
#    druid:
##     開啟filte
#      filters: stat,wall
#      stat-view-servlet:
#        enabled: true
#        login-username: druid
#        login-password: druid
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      aop-patterns:
#      - com.example.starter.*
##     設置filter細節
#      filter:
#        stat:
#          enabled: true
#        wall:
#          enabled: true